### ISSUE TITLE
Incomplete typing info for @command decorator

### ISSUE THREAD

**Issue by oliverandrich** [bckohan/django-typer#33]
![CleanShot 2024-03-04 at 22 12 15@2x](https://github.com/bckohan/django-typer/assets/758/2347bdf0-bff8-4669-b7bd-c2ae29b6bb1b)

If I use the example code, I see this message from mypy. The same applies to pyright. It seems as the type signature of command() is incomplete. May be it just helps to add Any as a type for args and kwargs?

**Comment by bckohan** [comment]
This also applies to group and initialize.

**Comment by oliverandrich** [comment]
Yes, I am using vscode. Until yesterday I was fully on Pylance/pyright for TypeChecking. But yesterday I decided to give mypy another try and it seems to work for me finally.
